#!/usr/bin/env bash
set -euo pipefail
# source "$(dirname "$0")/../lib.sh"
source "$LIBRARY_ROOT/engine-lib.sh"

( cd "${ENGINE_ROOT}/${DBLAB_ENGINE}"
    if [[ "${DBLAB_FORCE_REMOVE_VOLUMES:-}" == "true" ]]; then
        compose down -v
    else
        compose down
    fi
)

