#!/usr/bin/env bash
set -euo pipefail
# source "$(dirname "$0")/../lib.sh"
source "$DBLAB_ROOT/scripts/lib/engine-lib.sh"

( cd "${DBLAB_ROOT}/engines/${DBLAB_ENGINE}"
    if [[ "${DBLAB_FORCE_REMOVE_VOLUMES:-}" == "true" ]]; then
        compose down -v
    else
        compose down
    fi
)

