#!/usr/bin/env bash
set -euo pipefail
# source "$(dirname "$0")/../lib.sh"
source "$DBLAB_ROOT/scripts/lib/core.sh"

( cd "${DBLAB_ROOT}/engines/${DBLAB_ENGINE}"
    svc="${1:-}"
    if [[ -n "$svc" ]]; then
        compose -f compose.yaml restart "$svc"
    else
        compose -f compose.yaml --profile engine restart
    fi
)

