#!/usr/bin/env bash
set -euo pipefail
# source "$(dirname "$0")/../lib.sh"
source "$LIBRARY_ROOT/engine-lib.sh"

( cd "${ENGINE_ROOT}/${DBLAB_ENGINE}"
    svc="${1:-}"
    if [[ -n "$svc" ]]; then
        compose -f compose.yaml restart "$svc"
    else
        compose -f compose.yaml --profile engine restart
    fi
)

