#!/usr/bin/env bash
set -euo pipefail
source "$LIBRARY_ROOT/engine-lib.sh"

echo "postgresql://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@${HOST_BIND:-127.0.0.1}:${PGPORT:-55432}/${PGDATABASE:-postgres}"

