#!/usr/bin/env bash
set -euo pipefail
source "${ENGINE_ROOT}/${DBLAB_ENGINE}/lib.sh"

( cd "${ENGINE_ROOT}/${DBLAB_ENGINE}"
    if [[ "${DBLAB_FORCE_REMOVE_VOLUMES:-}" == "true" ]]; then
        compose -f compose.yaml --profile engine --profile cli down -v
    else
        compose -f compose.yaml --profile engine --profile cli down
    fi
)

