#!/usr/bin/env bash
set -euo pipefail
source "$DBLAB_ROOT/scripts/lib/engine-lib.sh"

( cd "$DBLAB_ROOT/engines/postgres"
    if [[ "${DBLAB_FORCE_REMOVE_VOLUMES:-}" == "true" ]]; then
        compose -f compose.yaml --profile engine --profile cli down -v
    else
        compose -f compose.yaml --profile engine --profile cli down
    fi
)

