#!/usr/bin/env bash
set -euo pipefail
source "${ENGINE_ROOT}/${DBLAB_ENGINE}/lib.sh"

( cd "${ENGINE_ROOT}/${DBLAB_ENGINE}"
    compose -f compose.yaml --profile engine run --rm --no-deps postgres \
		pg_isready -h ${PGHOST} -p ${PGPORT} -U "${PGUSER}" -d "${PGDATABASE}"

)

