#!/usr/bin/env bash
set -euo pipefail
source "$LIBRARY_ROOT/engine-lib.sh"

( cd "$ENGINE_ROOT/sqlserver"
    if [[ "${DBLAB_FORCE_REMOVE_VOLUMES:-}" == "true" ]]; then
        compose -f compose.yaml --profile engine --profile cli down -v
    else
        compose -f compose.yaml --profile engine --profile cli down
    fi
)

