services:
  db-tools:
    build:
      context: .
    container_name: db-lab-tools
    working_dir: /work
    volumes:
      - .:/work
    networks:
      - dblab

networks:
  dblab:
    external: true
    name: "${DB_LAB_NETWORK}"

